Description:  "CDK role for LITTIL Github repository"

Parameters:
  AccountName:
    Description : "AccountName"
    Type: "String"
    AllowedPattern : "staging|prod|shared"
  Country:
    Description : "Country (e.g. NL)"
    Type: "String"
    AllowedPattern : "NL"
  GitHubOrg:
    Type: String
    Default: Devoxx4Kids-NPO
    AllowedPattern: "Devoxx4Kids-NPO"
  RepositoryName:
    Description: "Github repository name"
    Type: String
    AllowedPattern: "littil-.*"

Resources:
  CdkRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Sub
        - "LITTIL-${Country}-${AccountName}-${Repo}-Cdk-Role"
        - Country: !Ref Country
          AccountName: !Ref AccountName
          Repo: !Ref RepositoryName
      Description: Role that is allowed to assume CDK roles
      Policies:
        - PolicyName: Assume-CDK-roles
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/cdk-*'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

# Local user, remove after pipeline
  CdkUser:
    Type: AWS::IAM::User
    Properties:
      UserName:
        !Sub
        - "LITTIL-${Country}-${AccountName}-${Repo}-Cdk-User"
        - Country: !Ref Country
          AccountName: !Ref AccountName
          Repo: !Ref RepositoryName
      Policies:
        - PolicyName: Assume-CDK-roles
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/cdk-*'

Outputs:
  CdkRole:
    Value: !GetAtt CdkRole.Arn
