Description:  "CDK role for LITTIL Github repository"

Parameters:
  Environment:
    Description : "Environment"
    Type: "String"
    AllowedPattern : "acc|prod"
  Country:
    Description : "Country (e.g. NL)"
    Type: "String"
    AllowedPattern : "NL"
  GitHubOrg:
    Type: String
    Default: Devoxx4Kids-NPO
    AllowedPattern: "Devoxx4Kids-NPO"
  RepositoryName:
    Description: "Github repository name"
    Type: String
    AllowedPattern: "littil-.*"

Resources:
  CdkRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Sub
        - "LITTIL-${Country}-${Env}-Cdk"
        - Country: !Ref Country
          Env: !Ref Environment
      Description: Role that is allowed to assume CDK roles
      Policies:
        - PolicyName: assumeRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/cdk-*'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  CdkRole:
    Value: !GetAtt CdkRole.Arn
