Description:  "CDK role for LITTIL Github repository"

Parameters:
  Environment:
    Description : "Environment"
    Type: "String"
    AllowedPattern : "acc|prod"
  Country:
    Description : "Country (e.g. NL)"
    Type: "String"
    AllowedPattern : "NL"
  GithubOrg:
    Type: String
    Default: Devoxx4Kids-NPO
    AllowedPattern: "Devoxx4Kids-NPO"
  FullRepoName:
    Description: "Github repository name, e.g. littil-frontend"
    Type: String
    AllowedPattern: "littil-.*"

Resources:
  CdkRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Sub
        - "LITTIL-${Country}-${Env}-Cdk"
        - Country: !Ref Country
          Env: !Ref Environment
      Description: Role that is allowed to assume CDK roles
      Path: /
      Policies:
        - PolicyName: assumeRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/cdk-*'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: [1234567891234567891234567891234567891234]
      ClientIdList:
        - !Sub https://github.com/${GithubOrg}

Outputs:
  Role:
    Value: !GetAtt CdkRole.Arn
